name: Build DEB Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Package
        run: |
          mkdir -p build/dists/stable/main/binary-all
          dpkg-deb --build package build/dists/stable/main/binary-all/ytdownloader_1.0.0_all.deb
          cd build/dists/stable/main/binary-all
          dpkg-scanpackages . | gzip -c > Packages.gz
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
