name: Build and Deploy

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and Index Package
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

          mkdir -p build/dists/stable/main/binary-all

          dpkg-deb --build package \
            build/dists/stable/main/binary-all/ytdownloader_1.0.0_all.deb

          cd build/dists/stable/main

          dpkg-scanpackages binary-all /dev/null > binary-all/Packages
          gzip -kf binary-all/Packages

          cd ..

          {
            echo "Origin: ytdownloader-repo"
            echo "Label: ytdownloader"
            echo "Suite: stable"
            echo "Codename: stable"
            echo "Architectures: all"
            echo "Components: main"
            echo "Description: YtDownloader Repository"
            echo "Date: $(date -Ru)"
            echo "MD5Sum:"
            printf " %s %16d %s\n" \
              "$(md5sum main/binary-all/Packages.gz | cut -d' ' -f1)" \
              "$(stat -c%s main/binary-all/Packages.gz)" \
              "main/binary-all/Packages.gz"

            echo "SHA256:"
            printf " %s %16d %s\n" \
              "$(sha256sum main/binary-all/Packages.gz | cut -d' ' -f1)" \
              "$(stat -c%s main/binary-all/Packages.gz)" \
              "main/binary-all/Packages.gz"
          } > Release

          cd ../../..

          cp install.sh build/install.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
